data_config:
  train_dir: tests/synthetic_data.json
  valid_dir: tests/synthetic_data.json
  test_dir: tests/synthetic_data.json
  data_format: json
  data_specs:
    num_event_types: 3
    pad_token_id: 3
    padding_side: right
    truncation_side: right
    padding_strategy: null
    truncation_strategy: null
    max_len: null
    fim_context_size: 16
    fim_inference_size: 16
    fim_max_num_events: 40
    fim_sampling_strategy: sequential
    fim_episodes_per_epoch: 20
base_config:
  stage: train
  backend: torch
  dataset_id: hawkes_local
  runner_id: std_tpp
  model_id: NHP
  base_dir: ./checkpoints/
  specs:
    log_folder: ./checkpoints/1528028_125644467540736_251219-144834
    saved_model_dir: ./checkpoints/1528028_125644467540736_251219-144834/models/saved_model
    saved_log_dir: ./checkpoints/1528028_125644467540736_251219-144834/log
    output_config_dir: ./checkpoints/1528028_125644467540736_251219-144834/NHP_train_hawkes_output.yaml
model_config:
  rnn_type: LSTM
  hidden_size: 64
  time_emb_size: 16
  num_layers: 2
  sharing_param_layer: false
  loss_integral_num_sample_per_step: 20
  dropout_rate: 0.0
  use_ln: false
  thinning:
    num_seq: 10
    num_sample: 1
    num_exp: 200
    look_ahead_time: 5
    patience_counter: 3
    over_sample_rate: 5
    num_samples_boundary: 5
    dtime_max: 5
    num_step_gen: 1
  num_event_types_pad: 4
  num_event_types: 3
  event_pad_index: 3
  model_id: NHP
  pretrained_model_dir: null
  gpu: 0
  model_specs: {}
trainer_config:
  seed: 42
  gpu: 0
  batch_size: 32
  max_epoch: 3
  shuffle: false
  optimizer: adam
  learning_rate: 0.001
  valid_freq: 1
  use_tfb: false
  metrics:
  - acc
  - rmse
